import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { ArrowRight, Eye, EyeOff, LockKeyhole, Mail, MapPin, UserRound } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { errorMessage, validationMessage } from '../api/client';
import { Button } from '../components/ui';
const loginSchema=z.object({email:z.string().email('Enter a valid email'),password:z.string().min(1,'Password is required')}); const registerSchema=z.object({fullName:z.string().min(2,'Please enter your full name'),email:z.string().email('Enter a valid email'),phone:z.string().min(8,'Enter a valid phone number'),neighborhood:z.string().min(2,'Tell us your neighborhood'),password:z.string().min(8,'Use at least 8 characters'),confirmPassword:z.string()}).refine(x=>x.password===x.confirmPassword,{path:['confirmPassword'],message:'Passwords do not match'});
export function Login(){const {login}=useAuth(),nav=useNavigate(),loc=useLocation();const [error,setError]=useState('');const form=useForm<z.infer<typeof loginSchema>>({resolver:zodResolver(loginSchema),defaultValues:{email:'customer@neighborlink.local',password:'NeighborLink@123'}});const submit=form.handleSubmit(async v=>{try{const u=await login(v.email,v.password);nav(u.role==='ADMIN'?'/admin':String(loc.state?.from??'/dashboard'));}catch(e){setError(errorMessage(e));}});return <AuthLayout title="Welcome back" subtitle="Sign in to find and manage your local services."><form onSubmit={submit} className="auth-form"><Field label="Email address" error={form.formState.errors.email?.message}><Mail size={18}/><input type="email" {...form.register('email')} /></Field><PasswordInput register={form.register('password')} error={form.formState.errors.password?.message}/>{error&&<p className="form-error">{error}</p>}<div className="row between"><label className="check"><input type="checkbox"/>Remember me</label><Link to="/forgot-password">Forgot password?</Link></div><Button disabled={form.formState.isSubmitting}>{form.formState.isSubmitting?'Signing in…':<>Sign in <ArrowRight size={18}/></>}</Button></form><p className="auth-switch">New to NeighborLink? <Link to="/register">Create an account</Link></p><DemoAccounts/></AuthLayout>}
export function Register(){const {register:join}=useAuth(),nav=useNavigate();const [error,setError]=useState('');const form=useForm<z.infer<typeof registerSchema>>({resolver:zodResolver(registerSchema)});const submit=form.handleSubmit(async({confirmPassword,...data})=>{try{await join(data);nav('/dashboard');}catch(e){setError(validationMessage(e));}});return <AuthLayout title="Join your neighborhood" subtitle="Create a free account to book a trusted local service."><form onSubmit={submit} className="auth-form"><Field label="Full name" error={form.formState.errors.fullName?.message}><UserRound size={18}/><input placeholder="Your name" {...form.register('fullName')}/></Field><div className="two-col"><Field label="Email" error={form.formState.errors.email?.message}><Mail size={18}/><input type="email" placeholder="you@example.com" {...form.register('email')}/></Field><Field label="Phone" error={form.formState.errors.phone?.message}><input placeholder="98765 43210" {...form.register('phone')}/></Field></div><Field label="Neighborhood" error={form.formState.errors.neighborhood?.message}><MapPin size={18}/><input placeholder="e.g. Central Area" {...form.register('neighborhood')}/></Field><PasswordInput register={form.register('password')} error={form.formState.errors.password?.message} label="Create a password"/><PasswordInput register={form.register('confirmPassword')} error={form.formState.errors.confirmPassword?.message} label="Confirm password"/><p className="tiny">By joining, you agree to treat your neighbors with respect.</p>{error&&<p className="form-error">{error}</p>}<Button disabled={form.formState.isSubmitting}>{form.formState.isSubmitting?'Creating account…':<>Create my account <ArrowRight size={18}/></>}</Button></form><p className="auth-switch">Already a member? <Link to="/login">Sign in</Link></p></AuthLayout>}
function PasswordInput({register,error,label='Password'}:{register:any;error?:string;label?:string}){const[visible,setVisible]=useState(false);return <Field label={label} error={error}><LockKeyhole size={18}/><input type={visible?'text':'password'} placeholder="••••••••" {...register}/><button type="button" className="input-icon" onClick={()=>setVisible(!visible)} aria-label="Show password">{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button></Field>}
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label className="field"><span>{label}</span><div className="input-wrap">{children}</div>{error&&<small className="field-error">{error}</small>}</label>}
function AuthLayout({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <div className="auth-page"><aside><Link className="brand light-brand" to="/"><span className="brand-mark">N</span>NeighborLink</Link><div><span className="eyebrow light">A stronger local community</span><h1>Good neighbors make every day easier.</h1><p>Join people who choose local, build trust, and help each other thrive.</p></div><div className="quote">“I found an amazing tutor just five minutes away.”<small>— Rhea, Central Area</small></div></aside><section className="auth-panel"><Link className="back-link" to="/">← Back to home</Link><div className="auth-box"><h2>{title}</h2><p>{subtitle}</p>{children}</div></section></div>}
function DemoAccounts(){return <div className="demo"><b>Demo accounts</b><span>Customer: customer@neighborlink.local</span><span>Provider: provider@neighborlink.local</span><span>Admin: admin@neighborlink.local</span><small>Password: NeighborLink@123</small></div>}
export function ForgotPassword(){return <AuthLayout title="Reset your password" subtitle="Enter your email and we’ll send reset instructions."><form className="auth-form" onSubmit={e=>{e.preventDefault();alert('Reset instructions would be sent in a connected email deployment.')}}><Field label="Email address"><Mail size={18}/><input type="email" placeholder="you@example.com" required/></Field><Button>Send reset link</Button></form><p className="auth-switch"><Link to="/login">Back to sign in</Link></p></AuthLayout>}
