import { useQuery } from '@tanstack/react-query';
import { CalendarDays, CheckCircle2, CircleDollarSign, Clock3, Heart, MessageCircle, Search, Star } from 'lucide-react';
import { Link } from 'react-router-dom';
import { request } from '../api/client';
import type { Booking, Page, Provider } from '../types';
import { useAuth } from '../context/AuthContext';
import { Avatar } from '../components/ProviderCard';
import { Card, Empty, Spinner, StatusBadge } from '../components/ui';
export default function Dashboard(){const{user}=useAuth();const bookings=useQuery({queryKey:['bookings'],queryFn:()=>request<Page<Booking>>('get','/bookings?limit=100')});const favorites=useQuery({queryKey:['favorites'],queryFn:()=>request<Provider[]>('get','/favorites')});const list=bookings.data?.items??[];const upcoming=list.filter(b=>['PENDING','ACCEPTED','IN_PROGRESS'].includes(b.status));const spent=list.filter(b=>b.payment?.status==='PAID').reduce((sum,b)=>sum+Number(b.quotedPrice),0);const isProvider=user?.role==='SERVICE_PROVIDER';const title=user?.fullName.split(' ')[0]??'Neighbor';return <div className="page dashboard"><section className="dashboard-welcome"><div><span className="eyebrow">{isProvider?'Provider home':'Your neighborhood hub'}</span><h1>Good {new Date().getHours()<12?'morning':'day'}, {title}.</h1><p>{isProvider?'Here’s what’s happening with your local business.':'Everything you need to manage local help, in one place.'}</p></div><Link className="btn" to={isProvider?'/bookings':'/services'}>{isProvider?'View requests':<><Search size={18}/>Find a service</>}</Link></section><div className="stats-grid"><Stat icon={<CalendarDays/>} label={isProvider?'New requests':'Upcoming bookings'} value={upcoming.length} accent="blue"/><Stat icon={<CheckCircle2/>} label="Completed services" value={list.filter(b=>b.status==='COMPLETED').length} accent="green"/><Stat icon={<Clock3/>} label="Pending requests" value={list.filter(b=>b.status==='PENDING').length} accent="amber"/><Stat icon={<CircleDollarSign/>} label={isProvider?'Paid earnings':'Total spent'} value={`₹${spent.toLocaleString()}`} accent="purple"/></div><div className="dashboard-grid"><section><div className="row between"><div><h2>{isProvider?'Booking requests':'Upcoming bookings'}</h2><p className="muted">Your next local plans at a glance.</p></div><Link to="/bookings">View all</Link></div>{bookings.isLoading?<div className="center"><Spinner/></div>:upcoming.length?<div className="booking-list">{upcoming.slice(0,4).map(b=><BookingRow key={b.id} booking={b} providerView={isProvider}/>)}</div>:<Empty title="No upcoming bookings" detail="Explore local services when you need a hand."/>}</section><aside><Card className="quick-search"><span className="eyebrow">Find help fast</span><h3>What can your neighborhood help with?</h3><div>{['Math tutoring','Home cleaning','Plumbing','Computer repair'].map(q=><Link key={q} to={`/services?q=${q}`}><Search size={15}/>{q}</Link>)}</div></Card><Card className="saved-card"><div className="row between"><h3><Heart size={18}/>Saved providers</h3><Link to="/favorites">See all</Link></div>{favorites.data?.length?<div className="avatar-stack">{favorites.data.slice(0,4).map(p=><Avatar key={p.id} name={p.user.fullName} url={p.user.avatarUrl}/>)}</div>:<p className="muted">Save providers you’d like to book later.</p>}</Card></aside></div></div>}
function Stat({icon,label,value,accent}:{icon:React.ReactNode;label:string;value:string|number;accent:string}){return <Card className={`stat ${accent}`}><span className="stat-icon">{icon}</span><div><b>{value}</b><p>{label}</p></div></Card>}
export function BookingRow({booking,providerView=false}:{booking:Booking;providerView?:boolean}){const person=providerView?booking.customer:booking.provider.user;return <Link to={`/bookings/${booking.id}`} className="booking-row"><Avatar name={person.fullName} url={person.avatarUrl}/><div className="grow"><b>{booking.service.title}</b><p>{person.fullName} · {new Date(booking.scheduledStart).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})} at {new Date(booking.scheduledStart).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</p></div><strong>₹{Number(booking.quotedPrice).toLocaleString()}</strong><StatusBadge status={booking.status}/></Link>}
