import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Send, MessageCircle } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { io } from 'socket.io-client';
import { request } from '../api/client';
import { useAuth } from '../context/AuthContext';
import { Avatar } from '../components/ProviderCard';
import { Button, Empty, Spinner } from '../components/ui';
type Conversation={id:string;booking?:{id:string;service:{title:string}};members:{user:{id:string;fullName:string;avatarUrl?:string}}[];messages:{id:string;body:string;createdAt:string}[]};type Message={id:string;body:string;createdAt:string;sender:{id:string;fullName:string;avatarUrl?:string}};
export default function Messages(){const {id}=useParams();const {user}=useAuth();const conversations=useQuery({queryKey:['conversations'],queryFn:()=>request<Conversation[]>('get','/conversations')});const active=id??conversations.data?.[0]?.id;const messages=useQuery({queryKey:['messages',active],enabled:!!active,queryFn:()=>request<{items:Message[]}>('get',`/conversations/${active}/messages`)});const qc=useQueryClient();const[text,setText]=useState('');const send=useMutation({mutationFn:()=>request<Message>('post',`/conversations/${active}/messages`,{body:text}),onSuccess:()=>{setText('');qc.invalidateQueries({queryKey:['messages',active]});qc.invalidateQueries({queryKey:['conversations']});}});useEffect(()=>{if(!active)return;const socket=io(import.meta.env.VITE_SOCKET_URL||'http://localhost:4000',{auth:{token:''}});socket.emit('conversation:join',active);socket.on('message:new',()=>{qc.invalidateQueries({queryKey:['messages',active]});qc.invalidateQueries({queryKey:['conversations']});});return()=>{socket.disconnect();};},[active,qc]);if(conversations.isLoading)return <div className="center tall"><Spinner/></div>;return <div className="page message-page"><section className="page-heading compact"><span className="eyebrow">Messages</span><h1>Keep the details close.</h1></section><div className="message-layout"><aside className="conversation-list"><h2>Conversations</h2>{conversations.data?.length?conversations.data.map(c=>{const other=c.members.find(m=>m.user.id!==user?.id)?.user;return <Link className={active===c.id?'conversation active':'conversation'} to={`/messages/${c.id}`} key={c.id}><Avatar name={other?.fullName??'Neighbor'} url={other?.avatarUrl}/><div className="grow"><b>{other?.fullName??'Neighbor'}</b><p>{c.messages[0]?.body??c.booking?.service.title??'Start chatting'}</p></div></Link>}):<Empty title="No conversations" detail="A chat opens when a provider accepts your booking."/>}</aside><section className="chat-window">{active?<><header>{(()=>{const c=conversations.data?.find(x=>x.id===active);const other=c?.members.find(m=>m.user.id!==user?.id)?.user;return <div className="row gap-sm"><Avatar name={other?.fullName??'Neighbor'} url={other?.avatarUrl}/><div><b>{other?.fullName}</b><p className="online-dot">Available for booking details</p></div></div>})()}</header><div className="message-feed">{messages.isLoading?<Spinner/>:messages.data?.items.map(m=><div key={m.id} className={m.sender.id===user?.id?'bubble mine':'bubble'}><p>{m.body}</p><small>{new Date(m.createdAt).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</small></div>)}</div><form className="compose" onSubmit={e=>{e.preventDefault();if(text.trim())send.mutate();}}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Write a message…"/><Button disabled={send.isPending||!text.trim()} aria-label="Send message"><Send size={18}/></Button></form></>:<Empty title="Choose a conversation" detail="Your messages will appear here."/>}</section></div></div>}
