import { Router } from 'express';
import { BookingStatus, Role, VerificationStatus } from '@prisma/client';
import { prisma } from '../config/prisma.js';
import { requireAuth, requireRole } from '../middleware/auth.js';
import { asyncRoute, ApiError, ok } from '../utils/api.js';
import { notify } from '../services/notifications.js';
const router = Router(); router.use(requireAuth, requireRole(Role.ADMIN));
const audit = (adminId: string, action: string, target: string, description: string) => prisma.auditLog.create({ data: { adminId, action, target, description } });
router.get('/overview', asyncRoute(async (_req, res) => {
  const [totalUsers, providers, activeBookings, completed, totalTransactions, openDisputes, recent, statusGroups, services, neighborhoods, latestUsers] = await Promise.all([
    prisma.user.count(), prisma.providerProfile.count({ where: { verificationStatus: VerificationStatus.VERIFIED } }), prisma.booking.count({ where: { status: { in: [BookingStatus.PENDING, BookingStatus.ACCEPTED, BookingStatus.IN_PROGRESS] } } }), prisma.booking.count({ where: { status: BookingStatus.COMPLETED } }), prisma.transaction.aggregate({ _sum: { grossAmount: true, platformFee: true } }), prisma.dispute.count({ where: { status: { in: ['OPEN', 'UNDER_REVIEW'] } } }), prisma.auditLog.findMany({ include: { admin: { select: { fullName: true } } }, orderBy: { createdAt: 'desc' }, take: 8 }), prisma.booking.groupBy({ by: ['status'], _count: true }), prisma.service.groupBy({ by: ['categoryId'], _count: true }), prisma.user.groupBy({ by: ['neighborhood'], _count: true, where: { neighborhood: { not: null } } }), prisma.user.findMany({ select: { createdAt: true }, orderBy: { createdAt: 'asc' } })
  ]);
  const cats = await prisma.serviceCategory.findMany({ where: { id: { in: services.map(s => s.categoryId) } } }); const days = Array.from({ length: 7 }, (_, i) => { const d = new Date(); d.setDate(d.getDate() - (6-i)); return d.toISOString().slice(0,10); }); const bookings = await prisma.booking.findMany({ where: { createdAt: { gte: new Date(Date.now()-7*86400000) } }, select: { createdAt: true, quotedPrice: true, status: true } });
  return ok(res, { metrics: { totalUsers, verifiedProviders: providers, activeBookings, completedServices: completed, totalRevenue: Number(totalTransactions._sum.grossAmount ?? 0), platformRevenue: Number(totalTransactions._sum.platformFee ?? 0), openDisputes }, charts: { userGrowth: days.map(day => ({ day: day.slice(5), users: latestUsers.filter(u => u.createdAt.toISOString().slice(0,10) === day).length })), bookingGrowth: days.map(day => ({ day: day.slice(5), bookings: bookings.filter(b => b.createdAt.toISOString().slice(0,10) === day).length, revenue: bookings.filter(b => b.createdAt.toISOString().slice(0,10) === day && b.status !== BookingStatus.CANCELLED).reduce((n,b) => n+Number(b.quotedPrice), 0) })), statuses: statusGroups.map(s => ({ name: s.status.replace('_',' '), value: s._count })), popularServices: services.map(s => ({ name: cats.find(c => c.id === s.categoryId)?.name ?? 'Other', value: s._count })).sort((a,b)=>b.value-a.value).slice(0,6), neighborhoods: neighborhoods.filter(n=>n.neighborhood).map(n=>({ name:n.neighborhood!, value:n._count })).sort((a,b)=>b.value-a.value).slice(0,6) }, recentActivity: recent });
}));
router.get('/users', asyncRoute(async (req, res) => { const page = Math.max(1, Number(req.query.page ?? 1)), limit = Math.min(50, Number(req.query.limit ?? 15)), q = String(req.query.q ?? ''); const where = q ? { OR: [{ fullName: { contains: q, mode: 'insensitive' as const } }, { email: { contains: q, mode: 'insensitive' as const } }] } : {}; const [items,total] = await prisma.$transaction([prisma.user.findMany({ where, select: { id:true,fullName:true,email:true,role:true,status:true,neighborhood:true,createdAt:true,providerProfile:{select:{verificationStatus:true}} }, orderBy:{createdAt:'desc'},skip:(page-1)*limit,take:limit }), prisma.user.count({where})]); return ok(res,{items,pagination:{page,limit,total,pages:Math.ceil(total/limit)}}); }));
router.patch('/users/:id/status', asyncRoute(async (req, res) => { const status = req.body.status === 'SUSPENDED' ? 'SUSPENDED' : 'ACTIVE'; const user = await prisma.user.update({ where: { id: req.params.id }, data: { status } }); await audit(req.auth!.id, `${status === 'SUSPENDED' ? 'Suspended' : 'Restored'} user`, user.id, `${user.email} account ${status.toLowerCase()}.`); return ok(res, { id:user.id,status:user.status }, `User ${status.toLowerCase()}.`); }));
router.get('/providers/pending-verification', asyncRoute(async (_req,res) => ok(res, await prisma.providerProfile.findMany({ where:{verificationStatus:VerificationStatus.PENDING},include:{user:{select:{id:true,fullName:true,email:true}},verifications:{where:{status:VerificationStatus.PENDING},select:{id:true,documentType:true,createdAt:true}}} }))));
router.post('/providers/:id/verification', asyncRoute(async (req,res) => { const status = req.body.approved ? VerificationStatus.VERIFIED : VerificationStatus.REJECTED; const provider = await prisma.providerProfile.update({where:{id:req.params.id},data:{verificationStatus:status}}); await prisma.verification.updateMany({where:{providerId:provider.id,status:VerificationStatus.PENDING},data:{status,adminNote:String(req.body.note ?? ''),reviewedAt:new Date()}}); await audit(req.auth!.id, status === VerificationStatus.VERIFIED ? 'Verified provider':'Rejected verification', provider.id, String(req.body.note ?? '')); await notify(provider.userId, 'Verification update', status === VerificationStatus.VERIFIED ? 'Your provider profile is now verified.' : 'Your verification needs resubmission.', 'VERIFICATION', '/dashboard'); return ok(res, provider, 'Verification decision recorded.'); }));
router.get('/transactions', asyncRoute(async (_req,res) => ok(res, await prisma.transaction.findMany({ include:{booking:{include:{customer:{select:{fullName:true}},provider:{include:{user:{select:{fullName:true}}}}}}},orderBy:{createdAt:'desc'},take:100 }))));
router.get('/disputes', asyncRoute(async (_req, res) => {
  const disputes = await prisma.dispute.findMany({
    include: { booking: { include: { service: true } }, raisedBy: { select: { fullName: true, email: true } } },
    orderBy: { createdAt: 'desc' }
  });
  return ok(res, disputes);
}));
router.post('/disputes/:id/resolve', asyncRoute(async (req,res) => { const value = req.body.outcome === 'PROVIDER' ? 'RESOLVED_PROVIDER' : 'RESOLVED_CUSTOMER'; const dispute = await prisma.dispute.update({where:{id:req.params.id},data:{status:value,adminNotes:String(req.body.adminNotes ?? ''),resolution:String(req.body.resolution ?? ''),resolvedAt:new Date()},include:{booking:true}}); await prisma.booking.update({where:{id:dispute.bookingId},data:{status: BookingStatus.COMPLETED}}); await audit(req.auth!.id,'Resolved dispute',dispute.id,dispute.resolution ?? ''); await notify(dispute.raisedById,'Dispute resolved',dispute.resolution ?? 'An administrator resolved your dispute.','DISPUTE',`/bookings/${dispute.bookingId}`); return ok(res,dispute,'Dispute resolved.'); }));
router.patch('/settings/platform-fee', asyncRoute(async (req,res) => { const fee=Number(req.body.value); if(!Number.isFinite(fee)||fee<0||fee>30) throw new ApiError(422,'Platform fee must be between 0% and 30%.','VALIDATION_ERROR'); const setting=await prisma.platformSetting.upsert({where:{key:'platformFeePercent'},create:{key:'platformFeePercent',value:String(fee)},update:{value:String(fee)}}); await audit(req.auth!.id,'Changed platform fee',setting.key,`${fee}%`); return ok(res,setting,'Platform fee updated.'); }));
export default router;
