import { Router } from 'express';
import { Prisma, Role, VerificationStatus } from '@prisma/client';
import { prisma } from '../config/prisma.js';
import { requireAuth, requireRole } from '../middleware/auth.js';
import { asyncRoute, ApiError, ok } from '../utils/api.js';

const router = Router();
const profileInclude = { user: { select: { id: true, fullName: true, avatarUrl: true, neighborhood: true, city: true, latitude: true, longitude: true } }, services: { where: { isActive: true }, include: { category: true } }, availability: true } as const;
const distanceKm = (aLat: number, aLng: number, bLat: number, bLng: number) => { const r = 6371, dLat = (bLat-aLat)*Math.PI/180, dLng = (bLng-aLng)*Math.PI/180; const n = Math.sin(dLat/2)**2 + Math.cos(aLat*Math.PI/180)*Math.cos(bLat*Math.PI/180)*Math.sin(dLng/2)**2; return 2*r*Math.atan2(Math.sqrt(n),Math.sqrt(1-n)); };
const presentProvider = (p: any, latitude?: number, longitude?: number) => { const { latitude: lat, longitude: lng, ...safeUser } = p.user; const distance = latitude != null && longitude != null && lat != null && lng != null ? Number(distanceKm(latitude, longitude, lat, lng).toFixed(1)) : null; const minPrice = p.services.reduce((acc: number, s: any) => Math.min(acc, Number(s.price)), Infinity); return { ...p, user: safeUser, startingPrice: Number.isFinite(minPrice) ? minPrice : null, distance, recommendationScore: Number((p.averageRating * 20 + p.completedJobs * .4 + p.experienceYears * 1.5 - (distance ?? 3) * .8).toFixed(1)) }; };

router.get('/categories', asyncRoute(async (_req, res) => ok(res, await prisma.serviceCategory.findMany({ where: { isActive: true }, orderBy: { name: 'asc' } }))));
router.get('/services', asyncRoute(async (req, res) => {
  const q = String(req.query.q ?? '').trim(); const category = String(req.query.category ?? ''); const verified = req.query.verified === 'true'; const rating = Number(req.query.rating ?? 0); const maxPrice = Number(req.query.maxPrice ?? 0); const maxDistance = Number(req.query.distance ?? 0); const latitude = req.query.latitude ? Number(req.query.latitude) : undefined; const longitude = req.query.longitude ? Number(req.query.longitude) : undefined; const page = Math.max(1, Number(req.query.page ?? 1)); const limit = Math.min(40, Math.max(1, Number(req.query.limit ?? 12)));
  const profiles = await prisma.providerProfile.findMany({ where: { isAcceptingWork: true, averageRating: { gte: rating || undefined }, verificationStatus: verified ? VerificationStatus.VERIFIED : undefined, services: { some: { isActive: true, ...(category ? { category: { slug: category } } : {}), ...(q ? { OR: [{ title: { contains: q, mode: 'insensitive' } }, { description: { contains: q, mode: 'insensitive' } }, { category: { name: { contains: q, mode: 'insensitive' } } }] } : {}), ...(maxPrice ? { price: { lte: maxPrice } } : {}) } } }, include: profileInclude });
  let result = profiles.map((p) => presentProvider(p, latitude, longitude)); if (maxDistance && latitude != null && longitude != null) result = result.filter(p => p.distance != null && p.distance <= maxDistance); result.sort((a,b) => b.recommendationScore-a.recommendationScore); const total = result.length;
  return ok(res, { items: result.slice((page-1)*limit, page*limit), pagination: { page, limit, total, pages: Math.ceil(total/limit) } });
}));
router.get('/providers', asyncRoute(async (req, res) => { const page = Math.max(1, Number(req.query.page ?? 1)); const limit = Math.min(40, Math.max(1, Number(req.query.limit ?? 12))); const profiles = await prisma.providerProfile.findMany({ where: { isAcceptingWork: true }, include: profileInclude, orderBy: [{ verificationStatus: 'asc' }, { averageRating: 'desc' }] }); const items = profiles.map(p => presentProvider(p, req.query.latitude ? Number(req.query.latitude) : undefined, req.query.longitude ? Number(req.query.longitude) : undefined)); return ok(res, { items: items.slice((page-1)*limit,page*limit), pagination: { page, limit, total: items.length, pages: Math.ceil(items.length/limit) } }); }));
router.get('/providers/:id', asyncRoute(async (req, res) => { const p = await prisma.providerProfile.findUnique({ where: { id: req.params.id }, include: { ...profileInclude, reviewsReceived: { include: { author: { select: { fullName: true, avatarUrl: true } } }, orderBy: { createdAt: 'desc' }, take: 20 } } }); if (!p) throw new ApiError(404, 'Provider not found.', 'PROVIDER_NOT_FOUND'); return ok(res, presentProvider(p)); }));
router.patch('/providers/me', requireAuth, requireRole(Role.SERVICE_PROVIDER), asyncRoute(async (req, res) => { const body = req.body as { bio?: string; skills?: string[]; experienceYears?: number; serviceRadiusKm?: number; isAcceptingWork?: boolean }; const p = await prisma.providerProfile.update({ where: { userId: req.auth!.id }, data: body, include: profileInclude }); return ok(res, presentProvider(p), 'Provider profile updated.'); }));
router.post('/providers/me/services', requireAuth, requireRole(Role.SERVICE_PROVIDER), asyncRoute(async (req, res) => { const { title, description, categoryId, price, durationMin } = req.body; if (!title || !description || !categoryId || !Number(price)) throw new ApiError(422, 'Please provide valid service details.', 'VALIDATION_ERROR'); const profile = await prisma.providerProfile.findUniqueOrThrow({ where: { userId: req.auth!.id } }); const service = await prisma.service.create({ data: { providerId: profile.id, title, description, categoryId, price: new Prisma.Decimal(price), durationMin: Number(durationMin) || 60 } }); return ok(res, service, 'Service published.', 201); }));
router.get('/favorites', requireAuth, asyncRoute(async (req, res) => { const rows = await prisma.favorite.findMany({ where: { userId: req.auth!.id }, include: { provider: { include: profileInclude } }, orderBy: { createdAt: 'desc' } }); return ok(res, rows.map(x => presentProvider(x.provider))); }));
router.post('/favorites/:providerId', requireAuth, asyncRoute(async (req, res) => { await prisma.favorite.upsert({ where: { userId_providerId: { userId: req.auth!.id, providerId: req.params.providerId } }, create: { userId: req.auth!.id, providerId: req.params.providerId }, update: {} }); return ok(res, null, 'Provider saved to favorites.', 201); }));
router.delete('/favorites/:providerId', requireAuth, asyncRoute(async (req, res) => { await prisma.favorite.delete({ where: { userId_providerId: { userId: req.auth!.id, providerId: req.params.providerId } } }).catch(() => null); return ok(res, null, 'Provider removed from favorites.'); }));
export default router;
