import { Router } from 'express';
import { BookingStatus } from '@prisma/client';
import { prisma } from '../config/prisma.js';
import { requireAuth } from '../middleware/auth.js';
import { asyncRoute, ApiError, ok } from '../utils/api.js';
import { reviewSchema } from '../validators/index.js';
import { notify } from '../services/notifications.js';
const router = Router();
router.post('/', requireAuth, asyncRoute(async (req, res) => { const body = reviewSchema.parse(req.body); const booking = await prisma.booking.findUnique({ where: { id: body.bookingId }, include: { provider: { include: { user: true } }, review: true } }); if (!booking || booking.customerId !== req.auth!.id) throw new ApiError(404, 'Completed booking not found.', 'BOOKING_NOT_FOUND'); if (booking.status !== BookingStatus.COMPLETED) throw new ApiError(409, 'Reviews can only be left after completed services.', 'REVIEW_NOT_ALLOWED'); if (booking.review) throw new ApiError(409, 'A review already exists for this booking.', 'REVIEW_EXISTS'); const review = await prisma.$transaction(async tx => { const r = await tx.review.create({ data: { ...body, authorId: req.auth!.id, providerId: booking.providerId } }); const ratings = await tx.review.aggregate({ where: { providerId: booking.providerId }, _avg: { rating: true }, _count: true }); await tx.providerProfile.update({ where: { id: booking.providerId }, data: { averageRating: ratings._avg.rating ?? 0, reviewCount: ratings._count } }); return r; }); await notify(booking.provider.userId, 'New review', `${req.auth!.email} left a ${body.rating}-star review.`, 'REVIEW', `/providers/${booking.providerId}`); return ok(res, review, 'Thanks for sharing your experience.', 201); }));
export default router;
