import { Router } from 'express';
import multer from 'multer';
import path from 'node:path';
import fs from 'node:fs';
import { Role, VerificationStatus } from '@prisma/client';
import { prisma } from '../config/prisma.js';
import { requireAuth, requireRole } from '../middleware/auth.js';
import { asyncRoute, ApiError, ok } from '../utils/api.js';
import { notify } from '../services/notifications.js';

const privateDir = path.resolve('uploads/private-verification'); fs.mkdirSync(privateDir, { recursive: true });
const upload = multer({ storage: multer.diskStorage({ destination: privateDir, filename: (_r, file, cb) => cb(null, `${Date.now()}-${Math.random().toString(36).slice(2)}${path.extname(file.originalname)}`) }), limits: { fileSize: 5 * 1024 * 1024 }, fileFilter: (_r, file, cb) => cb(null, ['application/pdf', 'image/jpeg', 'image/png', 'image/webp'].includes(file.mimetype)) });
const router = Router();
router.patch('/me', requireAuth, asyncRoute(async (req, res) => { const { fullName, phone, neighborhood, city, latitude, longitude } = req.body; const user = await prisma.user.update({ where: { id: req.auth!.id }, data: { ...(fullName ? { fullName: String(fullName).trim() } : {}), ...(phone !== undefined ? { phone: phone || null } : {}), ...(neighborhood !== undefined ? { neighborhood: neighborhood || null } : {}), ...(city !== undefined ? { city: city || null } : {}), ...(latitude !== undefined ? { latitude: Number(latitude) } : {}), ...(longitude !== undefined ? { longitude: Number(longitude) } : {}) }, select: { id: true, fullName: true, email: true, phone: true, role: true, neighborhood: true, city: true } }); return ok(res, user, 'Profile updated.'); }));
router.post('/me/become-provider', requireAuth, asyncRoute(async (req, res) => { const existing = await prisma.providerProfile.findUnique({ where: { userId: req.auth!.id } }); if (existing) throw new ApiError(409, 'You already have a provider profile.', 'PROVIDER_EXISTS'); const profile = await prisma.$transaction(async tx => { await tx.user.update({ where: { id: req.auth!.id }, data: { role: Role.SERVICE_PROVIDER } }); return tx.providerProfile.create({ data: { userId: req.auth!.id, bio: req.body.bio?.slice(0, 1000), skills: Array.isArray(req.body.skills) ? req.body.skills.slice(0, 20) : [], experienceYears: Number(req.body.experienceYears) || 0, serviceRadiusKm: Number(req.body.serviceRadiusKm) || 5 } }); }); return ok(res, profile, 'Your provider profile is ready. Submit verification when you are ready.', 201); }));
router.post('/me/verification', requireAuth, requireRole(Role.SERVICE_PROVIDER), upload.single('document'), asyncRoute(async (req, res) => { if (!req.file) throw new ApiError(422, 'Upload a PDF, PNG, JPG, or WEBP document under 5 MB.', 'INVALID_FILE'); const profile = await prisma.providerProfile.findUniqueOrThrow({ where: { userId: req.auth!.id } }); const verification = await prisma.verification.create({ data: { userId: req.auth!.id, providerId: profile.id, documentUrl: req.file.path, documentType: String(req.body.documentType ?? 'IDENTITY'), status: VerificationStatus.PENDING } }); await prisma.providerProfile.update({ where: { id: profile.id }, data: { verificationStatus: VerificationStatus.PENDING } }); const admins = await prisma.user.findMany({ where: { role: Role.ADMIN }, select: { id: true } }); await Promise.all(admins.map(a => notify(a.id, 'Provider verification submitted', 'A provider document is ready for review.', 'VERIFICATION', '/admin'))); return ok(res, { id: verification.id, status: verification.status }, 'Verification document submitted securely.', 201); }));
export default router;
