import express from 'express';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import swaggerJsdoc from 'swagger-jsdoc';
import swaggerUi from 'swagger-ui-express';
import { env } from './config/env.js';
import { errorHandler, notFound } from './middleware/error.js';
import authRoutes from './routes/auth.js';
import marketplaceRoutes from './routes/marketplace.js';
import bookingRoutes from './routes/bookings.js';
import paymentRoutes, { handleStripeWebhook } from './routes/payments.js';
import communicationRoutes from './routes/communication.js';
import userRoutes from './routes/users.js';
import adminRoutes from './routes/admin.js';
import reviewRoutes from './routes/reviews.js';
import { asyncRoute, ok } from './utils/api.js';

export const app = express();
app.set('trust proxy', 1);
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use(cors({ origin: env.CLIENT_URL, credentials: true }));
app.post('/api/payments/webhook', express.raw({ type: 'application/json' }), asyncRoute(async (req, res) => ok(res, { event: await handleStripeWebhook(req.body, req.headers['stripe-signature'] as string | undefined) }, 'Webhook processed.')));
app.use(express.json({ limit: '1mb' })); app.use(cookieParser());
app.use('/api', rateLimit({ windowMs: 15 * 60_000, max: 350, standardHeaders: 'draft-8', legacyHeaders: false, message: { success: false, message: 'Too many requests. Please try again shortly.', errorCode: 'RATE_LIMITED' } }));
app.get('/api/health', (_req, res) => ok(res, { status: 'healthy', service: 'NeighborLink API' }));
const spec = swaggerJsdoc({ definition: { openapi: '3.0.3', info: { title: 'NeighborLink API', version: '1.0.0', description: 'Local community services marketplace API.' }, servers: [{ url: '/api' }], components: { securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } } } }, apis: [] });
app.use('/api/docs', swaggerUi.serve, swaggerUi.setup({ ...spec, paths: { '/auth/login': { post: { summary: 'Sign in', requestBody: { required: true }, responses: { '200': { description: 'Authenticated' } } } }, '/services': { get: { summary: 'Search nearby services', responses: { '200': { description: 'Providers returned' } } } }, '/bookings': { get: { summary: 'Get authenticated bookings', security: [{ bearerAuth: [] }], responses: { '200': { description: 'Bookings returned' } } }, post: { summary: 'Create a booking request', security: [{ bearerAuth: [] }], responses: { '201': { description: 'Booking created' } } } } } }));
app.use('/api/auth', authRoutes); app.use('/api/users', userRoutes); app.use('/api', marketplaceRoutes); app.use('/api/bookings', bookingRoutes); app.use('/api/payments', paymentRoutes); app.use('/api', reviewRoutes); app.use('/api', communicationRoutes); app.use('/api/admin', adminRoutes);
app.use(notFound); app.use(errorHandler);
